name: build kantv
on:
  workflow_dispatch:
    inputs:
      release_tag:
        required: false
        type: string
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
          fetch-depth: '0'
        
      - name: build android release
        run: |
          source build/envsetup.sh  
          ./build/prebuild-download.sh  
          lunch 1  
          ./build-all.sh android

      - name: upload arm64-v8a release
        uses: actions/upload-artifact@v4
        if: ${{  success() }}
        with:
          name: arm64-v8a 
          path: ${{ github.workspace }}/cdeosplayer/kantv/build/outputs/apk/all64/release/*signed*.apk
